# --------------------------------------------------------------
# HP SALES DECK GENERATOR — FINAL + FIXED + COMPLETE VERSION
# --------------------------------------------------------------
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import os
import json

# ----------------------
# BRAND COLORS / FONTS
# ----------------------
BRAND_PRIMARY = RGBColor(0, 66, 121)
BRAND_SECONDARY = RGBColor(0, 132, 180)
TEXT_COLOR = RGBColor(34, 34, 34)
FOOTER_COLOR = RGBColor(120, 120, 120)
FONT_NAME = 'Calibri'


# ----------------------
# Utilities
# ----------------------
def set_font(p, size, bold=False, color=TEXT_COLOR):
    """Applies font settings safely to paragraph runs."""
    for run in p.runs:
        run.font.name = FONT_NAME
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = color


def add_footer(slide, text):
    """Adds a standard footer."""
    box = slide.shapes.add_textbox(Inches(0.6), Inches(7.0), Inches(9), Inches(0.4))
    p = box.text_frame.paragraphs[0]
    p.text = text
    p.alignment = PP_ALIGN.LEFT
    set_font(p, 9, color=FOOTER_COLOR)


# ----------------------
# Slide 1 — Title
# ----------------------


def slide_title(prs, pdf_title):
    # Blank slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Create a text box centered horizontally
    left = Inches(1)
    top = Inches(2)
    width = Inches(8)     # wide enough to wrap naturally
    height = Inches(2)    # tall enough for 2–3 lines

    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.clear()  # remove auto-placeholder paragraph

    # Add paragraph
    p = tf.paragraphs[0]
    p.text = pdf_title
    p.alignment = PP_ALIGN.CENTER

    # Set font
    font = p.font
    font.bold = True
    font.size = Pt(34)
    font.color.rgb = BRAND_PRIMARY

    # Let PowerPoint wrap text automatically
    tf.word_wrap = True

    # AUTO-SHRINK (Important)
    # ensures long titles shrink instead of overflowing
    tf.auto_size = True

    add_footer(slide, "Generated by HP AI Sales Assistant")
    return slide



# ----------------------
# Slide 2 — User Query + Requirements
# ----------------------
def slide_requirements(prs, query, extracted_req):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Title
    header = slide.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(9), Inches(0.7)).text_frame
    header.text = "Customer Requirements"
    set_font(header.paragraphs[0], 22, bold=True, color=BRAND_PRIMARY)

    # User Query
    qbox = slide.shapes.add_textbox(Inches(0.6), Inches(1.3), Inches(8.5), Inches(1.2)).text_frame
    qbox.text = "User Query:"
    set_font(qbox.paragraphs[0], 16, bold=True)

    p = qbox.add_paragraph()
    p.text = query
    set_font(p, 14)

    # Requirements Section
    rbox = slide.shapes.add_textbox(Inches(0.6), Inches(2.8), Inches(8.5), Inches(4.8)).text_frame
    rbox.text = "Extracted Requirements:"
    set_font(rbox.paragraphs[0], 16, bold=True, color=BRAND_SECONDARY)

    for req in extracted_req:
        p = rbox.add_paragraph()
        p.text = f"• {req}"
        set_font(p, 14)

    add_footer(slide, "Customer Requirement Analysis")
    return slide


# # ----------------------
# # Slide 3–7 — Product Pages
# # ----------------------


def slide_product(prs, product):
    """
    Product slide:
    - Left 1/3 = image + description
    - Right 2/3 = specs table
    """
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # -------------------------
    # Title
    # -------------------------
    title = product.get("model") or product.get("product_name") or "Unnamed Product"
    tbox = slide.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(9), Inches(0.7)).text_frame
    tbox.text = title
    set_font(tbox.paragraphs[0], 22, bold=True, color=BRAND_PRIMARY)

    # Left column: 1/3 width
    LEFT_X = Inches(0.6)
    LEFT_W = Inches(3.0)

    # -------------------------
    # IMAGE AREA (top-left)
    # -------------------------
    img_y = Inches(1.3)
    img_h = Inches(3.0)

    img_path = product.get("image_path")
    if img_path and os.path.exists(img_path):
        slide.shapes.add_picture(img_path, LEFT_X, Inches(1.4), width=LEFT_W, height=Inches(3.4))
    else:
        ph = slide.shapes.add_textbox(LEFT_X, img_y, LEFT_W, img_h)
        ph.text_frame.text = "Image not available"
        set_font(ph.text_frame.paragraphs[0], 12, bold=True)

    # -------------------------
    # DESCRIPTION (below image)
    # -------------------------
    desc = product.get("description", "")
    desc_y = Inches(1.3) + img_h + Inches(0.3)
    desc_h = Inches(2.5)  # controlled box height

    desc_box = slide.shapes.add_textbox(LEFT_X, desc_y, LEFT_W, desc_h)
    tf = desc_box.text_frame
    tf.word_wrap = True

    if desc:
        # Split into lines safely
        lines = desc.split("\n")

        # Ensure max 10 lines
        if len(lines) > 10:
            lines = lines[:9] + [lines[9][:50] + " ..."]

        # Write description line-by-line
        tf.text = "Description:"
        set_font(tf.paragraphs[0], 14, bold=True, color=BRAND_SECONDARY)

        for line in lines:
            p = tf.add_paragraph()
            p.text = line.strip()
            p.level = 1
            set_font(p, 12)

    else:
        tf.text = "Description not available"
        set_font(tf.paragraphs[0], 12, bold=True)

    # -------------------------
    # SPECIFICATIONS (right 2/3)
    # -------------------------
    specs = {}
    for key, val in product.items():
        if key.startswith("spec_") and val not in (None, "", []):
            clean = key.replace("spec_", "").replace("_", " ").title()
            specs[clean] = val

    if specs:
        table_x = Inches(4.0)     # 2/3 area starts here
        table_y = Inches(1.3)
        table_w = Inches(5.4)
        table_h = Inches(5.5)

        rows = len(specs) + 1
        table = slide.shapes.add_table(rows, 2, table_x, table_y, table_w, table_h).table

        # Headers
        table.cell(0, 0).text = "Specification"
        table.cell(0, 1).text = "Details"
        set_font(table.cell(0, 0).text_frame.paragraphs[0], 12, bold=True)
        set_font(table.cell(0, 1).text_frame.paragraphs[0], 12, bold=True)

        # Data
        for i, (k, v) in enumerate(specs.items(), start=1):
            table.cell(i, 0).text = k
            table.cell(i, 1).text = str(v)
            set_font(table.cell(i, 0).text_frame.paragraphs[0], 10)
            set_font(table.cell(i, 1).text_frame.paragraphs[0], 10)

    add_footer(slide, f"{title} — Product Details")
    return slide



# # ----------------------
# # Slide 8 — Full Comparison Table (Refactored)
# # ----------------------


def slide_comparison(prs, products, specs_list):
    """
    Compare all products using pre-extracted specs_list.
    specs_list = [ {spec: value}, {spec: value}, ... ]
    """
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Header
    header = slide.shapes.add_textbox(Inches(0.3), Inches(0.5), Inches(9), Inches(0.7)).text_frame
    header.text = "Product Comparison"
    set_font(header.paragraphs[0], 22, bold=True, color=BRAND_PRIMARY)

    # --------------------------------------------
    # Collect all unique spec keys across products
    # --------------------------------------------
    all_keys = set()
    for specs in specs_list:
        all_keys.update([k for k, v in specs.items() if v not in (None, "", [])])

    all_keys = sorted(all_keys)

    rows = len(all_keys) + 1
    cols = len(products) + 1

    # Table
    table = slide.shapes.add_table(
        rows, cols, Inches(0.3), Inches(1.3), Inches(9.4), Inches(5.4)
    ).table

    # --------------------------------------------
    # Header Row
    # --------------------------------------------
    table.cell(0, 0).text = "Feature"
    set_font(table.cell(0, 0).text_frame.paragraphs[0], 11, bold=True)

    for i, prod in enumerate(products):
        name = prod.get("model") or prod.get("product_name") or f"Product {i+1}"
        table.cell(0, i + 1).text = name
        set_font(table.cell(0, i + 1).text_frame.paragraphs[0], 11, bold=True)

    # --------------------------------------------
    # Body Rows
    # --------------------------------------------
    for r, key in enumerate(all_keys, start=1):
        table.cell(r, 0).text = key
        set_font(table.cell(r, 0).text_frame.paragraphs[0], 10, bold=True)

        for c, specs in enumerate(specs_list, start=1):
            val = specs.get(key, "N/A")
            table.cell(r, c).text = str(val)
            set_font(table.cell(r, c).text_frame.paragraphs[0], 9)

    add_footer(slide, "Comparison Across Recommended Products")
    return slide




# ----------------------
# Slide 9 — Upsell Products
# ----------------------
def slide_upsell(prs, upsells):
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    header = slide.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(9), Inches(0.7)).text_frame
    header.text = "Upsell Options"
    set_font(header.paragraphs[0], 22, bold=True, color=BRAND_PRIMARY)

    body = slide.shapes.add_textbox(Inches(0.6), Inches(1.3), Inches(8.5), Inches(5.4)).text_frame

    for up in upsells[:6]:
        if isinstance(up, dict):
            name = up.get("product_name", "Unnamed")
            price = up.get("price", "N/A")
        else:
            name = str(up)
            price = "N/A"

        p = body.add_paragraph()
        p.text = f"• {name} — {price}"
        set_font(p, 14)

    add_footer(slide, "Upsell Suggestions")
    return slide


# ----------------------
# Slide 10 — Conclusion
# ----------------------
def slide_conclusion(prs, conclusion_text):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    box = slide.shapes.add_textbox(Inches(0.6), Inches(1.4), Inches(9), Inches(3.5)).text_frame
    box.text = conclusion_text
    set_font(box.paragraphs[0], 18)
    add_footer(slide, "Thank You — HP Sales Team")
    return slide


# ----------------------
# MAIN GENERATOR (Final Version)
# ----------------------
def create_professional_ppt(
    sales_pitch=None,
    products=None,
    customer_query=None,
    output_file=None
):
    # Debug Prints
    print("\n=== DEBUG: SALES PITCH ===")
    print(json.dumps(sales_pitch, indent=4) if sales_pitch else "None")

    print("\n=== DEBUG: PRODUCTS ===")
    for p in products or []:
        print(json.dumps(p, indent=4))

    print("\n=== DEBUG: QUERY ===")
    print(customer_query)

    # Normalize Inputs
    pdf_title = sales_pitch.get("pitch_summary", "HP Proposal") if sales_pitch else "HP Proposal"
    extracted_requirements = sales_pitch.get("extracted_requirements", [])
    upsell_products = sales_pitch.get("upsell_opportunities", [])
    conclusion_text = sales_pitch.get("conclusion", "Recommended next steps")
    products = products or []
    output_file = output_file or "HP_Proposal.pptx"
    customer_query = customer_query or ""

    # Build PPT
    prs = Presentation()

    slide_title(prs, pdf_title)
    slide_requirements(prs, customer_query, extracted_requirements)

    # Individual Product Slides
    for prod in products[:5]:
        slide_product(prs, prod)

    
    def extract_specs(product):
        """
        Extracts all spec_* fields and returns a clean dict:
        {
            "Processor": "Intel i5",
            "Ram": "16GB",
            ...
        }
        """
        specs = {}

        for key, value in product.items():
            if key.startswith("spec_") and value not in (None, "", []):
                clean_key = key.replace("spec_", "").replace("_", " ").title()
                specs[clean_key] = value

        return specs

    
    
    # ----------------------
    # Build Specs Dictionary from spec_* keys
    # ----------------------
    specs_list = []

    for p in products:
        p["specs"] = extract_specs(p)
        specs_list.append(p["specs"])


    slide_comparison(prs, products,specs_list)
    slide_upsell(prs, upsell_products)
    slide_conclusion(prs, conclusion_text)

    prs.save(output_file)
    print(f"\n🎉 SUCCESS: PowerPoint generated → {output_file}")
    return output_file

