# --------------------------------------------------------------
# HP SALES DECK GENERATOR — FINAL + FIXED + COMPLETE VERSION
# --------------------------------------------------------------
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from io import BytesIO
import requests
import os
import json
from PIL import Image

# ----------------------
# BRAND COLORS / FONTS
# ----------------------
BRAND_PRIMARY   = RGBColor(0, 66, 121)   # HP blue
BRAND_SECONDARY = RGBColor(0, 132, 180)
TEXT_COLOR      = RGBColor(34, 34, 34)
FOOTER_COLOR    = RGBColor(120, 120, 120)
FONT_NAME       = "Calibri"

# ===============================================================
# COMMON HELPERS
# ===============================================================
def set_font(p, size, bold=False, color=TEXT_COLOR):
    """Applies font settings safely to paragraph runs."""
    for run in p.runs:
        run.font.name = FONT_NAME
        run.font.size = Pt(size)
        run.font.bold = bold
        run.font.color.rgb = color

def add_footer(slide, text):
    """Adds a standard footer in bottom-left."""
    box = slide.shapes.add_textbox(Inches(0.6), Inches(7.0),
                                   Inches(9), Inches(0.4))
    tf = box.text_frame
    p = tf.paragraphs[0]
    p.text = text
    p.alignment = PP_ALIGN.LEFT
    set_font(p, 9, color=FOOTER_COLOR)

def apply_soft_gradient_background(slide):
    """
    Light violet/blue gradient like your screenshots
    (used on intro / requirements / comparison / upsell / conclusion).
    """
    fill = slide.background.fill
    fill.gradient()
    stops = fill.gradient_stops
    # ensure at least 2 stops exist
    while len(stops) < 2:
        stops.add()
    stops[0].position = 0
    stops[0].color.rgb = RGBColor(245, 248, 255)   # very light blue
    stops[1].position = 1
    stops[1].color.rgb = RGBColor(236, 234, 252)   # very light violet
    fill.gradient_angle = 45


SLIDE_WIDTH  = Inches(10)
SLIDE_HEIGHT = Inches(7.5)

CONTENT_WIDTH = Inches(8)   # equal left–right margin
SIDE_MARGIN   = (SLIDE_WIDTH - CONTENT_WIDTH) / 2


# ===============================================================
# SLIDE 0 — STATIC COVER (SCREENSHOT 1)
# ===============================================================
def slide_static_cover(prs):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_soft_gradient_background(slide)

    box_height = Inches(2.0)
    box_top = (SLIDE_HEIGHT - box_height) / 2

    box = slide.shapes.add_textbox(
        SIDE_MARGIN,
        box_top,
        CONTENT_WIDTH,
        box_height
    )

    tf = box.text_frame
    tf.clear()

    p = tf.paragraphs[0]
    p.text = "HP Professional Product Recommendation"
    p.alignment = PP_ALIGN.CENTER
    set_font(p, 36, bold=True, color=BRAND_PRIMARY)

    p2 = tf.add_paragraph()
    p2.text = "Curated Solutions for User-Specific Needs"
    p2.alignment = PP_ALIGN.CENTER
    set_font(p2, 18, color=FOOTER_COLOR)

    p3 = tf.add_paragraph()
    p3.text = "Generated by HP AI Sales Assistant"
    p3.alignment = PP_ALIGN.CENTER
    set_font(p3, 18, color=FOOTER_COLOR)

    return slide


# ===============================================================
# SLIDE 1 — INTRO PARAGRAPH (SCREENSHOT 2)
# ===============================================================
def slide_intro(prs, intro_text):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_soft_gradient_background(slide)

    box_height = Inches(2.6)
    box_top = (SLIDE_HEIGHT - box_height) / 2

    box = slide.shapes.add_textbox(
        SIDE_MARGIN,
        box_top,
        CONTENT_WIDTH,
        box_height
    )

    tf = box.text_frame
    tf.word_wrap = True

    p = tf.paragraphs[0]
    p.text = intro_text or ""
    p.alignment = PP_ALIGN.LEFT
    set_font(p, 20)

    footer_box = slide.shapes.add_textbox(
        SIDE_MARGIN,
        box_top + box_height + Inches(0.3),
        CONTENT_WIDTH,
        Inches(0.3)
    )

    ftf = footer_box.text_frame
    fp = ftf.paragraphs[0]
    fp.text = "Generated by HP AI Sales Assistant"
    set_font(fp, 11, color=FOOTER_COLOR)
    fp.alignment = PP_ALIGN.LEFT

    return slide


# ===============================================================
# SLIDE 2 — CUSTOMER REQUIREMENTS (SCREENSHOT 3)
# ===============================================================
def slide_requirements(prs, query, extracted_req):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_soft_gradient_background(slide)

    # Title
    header_tf = slide.shapes.add_textbox(
        Inches(0.8), Inches(0.7), Inches(9), Inches(0.7)
    ).text_frame
    header_tf.text = "Customer Requirements"
    set_font(header_tf.paragraphs[0], 26, bold=True, color=BRAND_PRIMARY)

    # User Query label + text
    qbox_tf = slide.shapes.add_textbox(
        Inches(0.8), Inches(1.7), Inches(8.8), Inches(1.0)
    ).text_frame
    qbox_tf.text = "User Query:"
    set_font(qbox_tf.paragraphs[0], 16, bold=True)

    qp = qbox_tf.add_paragraph()
    qp.text = query or ""
    set_font(qp, 14, bold=False)

    # Extracted Requirements
    rbox_tf = slide.shapes.add_textbox(
        Inches(0.8), Inches(3.0), Inches(8.8), Inches(3.8)
    ).text_frame
    rbox_tf.text = "Extracted Requirements:"
    set_font(rbox_tf.paragraphs[0], 16, bold=True, color=BRAND_SECONDARY)

    for key, value in (extracted_req or {}).items():
        if isinstance(value, dict):
            p = rbox_tf.add_paragraph()
            p.text = f"• {key.replace('_', ' ').title()}:"
            set_font(p, 14, bold=True)

            for sub_k, sub_v in value.items():
                sp = rbox_tf.add_paragraph()
                sp.text = f"   ○ {sub_k.replace('_', ' ').title()}: {sub_v}"
                set_font(sp, 13)
        else:
            p = rbox_tf.add_paragraph()
            p.text = f"• {key.replace('_', ' ').title()}: {value}"
            set_font(p, 14)

    add_footer(slide, "Customer Requirement Analysis")
    return slide



def add_product_image_safe(slide, image_bytes, left, top, box_width, box_height):
    """Safely fit image inside bounding box without overflow."""
    
    # Place initially
    pic = slide.shapes.add_picture(image_bytes, left, top)

    # Original aspect ratio
    img_ratio = pic.width / pic.height
    box_ratio = box_width / box_height

    # Scale inside box
    if img_ratio > box_ratio:
        # Fit to width
        pic.width = box_width
        pic.height = int(box_width / img_ratio)
    else:
        # Fit to height
        pic.height = box_height
        pic.width = int(box_height * img_ratio)

    # Center inside bounding box
    pic.left = left + int((box_width - pic.width) / 2)
    pic.top  = top  + int((box_height - pic.height) / 2)



from pptx.enum.shapes import MSO_SHAPE

def add_white_card(slide, left, top, width, height, radius=18):
    """
    Draws a white rounded rectangle "card" for product images.
    """
    card = slide.shapes.add_shape(
        MSO_SHAPE.ROUNDED_RECTANGLE,
        left, top, width, height
    )

    fill = card.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(255, 255, 255)

    line = card.line
    line.color.rgb = RGBColor(220, 220, 220)
    line.width = Pt(0.75)

    # Subtle soft shadow effect
    card.shadow.inherit = False
    card.shadow.visible = True
    card.shadow.blur_radius = Pt(6)
    card.shadow.distance = Pt(2)


from pptx.enum.shapes import MSO_SHAPE

def add_white_circle_card(slide, left, top, diameter):
    """
    Draws a perfect white circular card for product images.
    """
    circle = slide.shapes.add_shape(
        MSO_SHAPE.OVAL,
        left,
        top,
        diameter,   # width = height = diameter
        diameter
    )

    # White fill
    fill = circle.fill
    fill.solid()
    fill.fore_color.rgb = RGBColor(255, 255, 255)

    # Soft border
    line = circle.line
    line.color.rgb = RGBColor(220, 220, 220)
    line.width = Pt(0.75)

    # Subtle shadow for floating effect
    circle.shadow.inherit = False
    circle.shadow.visible = True
    circle.shadow.blur_radius = Pt(6)
    circle.shadow.distance = Pt(2)



# ===============================================================
# PRODUCT PAGES (SCREENSHOT 4)
# ===============================================================
def extract_section_for_product(raw_text, product_title):
    """Extracts bullet points for ONE product from a multi-product markdown section."""
    if not raw_text or not product_title:
        return []
    blocks = raw_text.split("---")
    for block in blocks:
        if product_title.lower() in block.lower():
            lines = block.splitlines()
            clean = []
            for line in lines:
                line = line.strip()
                if line.startswith("-"):
                    clean.append(line.replace("- ", "").strip())
            return clean
    return []

def slide_product(prs, product, sales_pitch):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_soft_gradient_background(slide)
    # Product slides are white (like screenshot 4)

    # Title
    title = product.get("model") or product.get("product_name") or "Unnamed Product"
    title_box = slide.shapes.add_textbox(
        Inches(0.8), Inches(0.6), Inches(7.0), Inches(0.9)
    )
    tf = title_box.text_frame
    tf.text = title
    set_font(tf.paragraphs[0], 28, bold=True, color=BRAND_PRIMARY)

    # ==========================================================
    # PRODUCT IMAGE WITH WHITE CARD (PRODUCTION-GRADE LOOK)
    # ==========================================================

    # # Card position (slightly bigger than image)
    # card_x, card_y = Inches(6.85), Inches(0.55)
    # card_w, card_h = Inches(3.0), Inches(3.3)

    # add_white_card(slide, card_x, card_y, card_w, card_h)

    card_x = Inches(6.85)
    card_y = Inches(0.55)
    card_diameter = Inches(3.0)

    add_white_circle_card(
        slide,
        card_x,
        card_y,
        card_diameter
    )


    # Image position INSIDE the card (with padding)
    img_x, img_y = Inches(7.3), Inches(0.7)
    img_w, img_h = Inches(2.2), Inches(2.6)

    cloud_url = product.get("cloud_url")

    if cloud_url:
        try:
            resp = requests.get(cloud_url, timeout=10)
            resp.raise_for_status()

            add_product_image_safe(
                slide,
                BytesIO(resp.content),   # ✅ RAW IMAGE, NO BACKGROUND REMOVAL
                img_x,
                img_y,
                img_w,
                img_h
            )

        except Exception:
            ph = slide.shapes.add_textbox(img_x, img_y, img_w, img_h)
            ph.text_frame.text = "Image not available"
            set_font(ph.text_frame.paragraphs[0], 12, bold=True)
    else:
        ph = slide.shapes.add_textbox(img_x, img_y, img_w, img_h)
        ph.text_frame.text = "Image not available"
        set_font(ph.text_frame.paragraphs[0], 12, bold=True)




    # Extract product-specific bullets
    raw_highlights = sales_pitch.get("product_highlights", "")
    raw_reasons    = sales_pitch.get("reasons_to_buy", "")
    raw_advantage  = sales_pitch.get("competitive_advantages", "")

    highlights = extract_section_for_product(raw_highlights, title)
    reasons    = extract_section_for_product(raw_reasons, title)
    advantages = extract_section_for_product(raw_advantage, title)

    # Key Product Highlights
    hl_box = slide.shapes.add_textbox(
        Inches(0.8), Inches(1.7), Inches(6.4), Inches(1.9)
    )
    tf = hl_box.text_frame
    tf.word_wrap = True
    tf.text = "Key Product Highlights"
    set_font(tf.paragraphs[0], 18, bold=True, color=BRAND_SECONDARY)

    if highlights:
        for item in highlights[:5]:
            p = tf.add_paragraph()
            p.text = f"• {item}"
            p.level = 1
            set_font(p, 12)
    else:
        p = tf.add_paragraph()
        p.text = "Highlights not available"
        set_font(p, 12)

    # Why Customers Should Buy This
    rb_box = slide.shapes.add_textbox(
        Inches(0.8), Inches(3.8), Inches(9.0), Inches(1.6)
    )
    tf = rb_box.text_frame
    tf.word_wrap = True
    tf.text = "Why Customers Should Buy This"
    set_font(tf.paragraphs[0], 18, bold=True, color=BRAND_PRIMARY)

    if reasons:
        for item in reasons[:4]:
            p = tf.add_paragraph()
            p.text = f"✔ {item}"
            p.level = 1
            set_font(p, 12)
    else:
        p = tf.add_paragraph()
        p.text = "Buying reasons not available"
        set_font(p, 12)

    # Competitive Advantages
    ca_box = slide.shapes.add_textbox(
        Inches(0.8), Inches(5.6), Inches(9.0), Inches(1.6)
    )
    tf = ca_box.text_frame
    tf.word_wrap = True
    tf.text = "Competitive Advantages"
    set_font(tf.paragraphs[0], 18, bold=True, color=BRAND_SECONDARY)

    if advantages:
        for item in advantages[:4]:
            p = tf.add_paragraph()
            p.text = f"★ {item}"
            p.level = 1
            set_font(p, 12)
    else:
        p = tf.add_paragraph()
        p.text = "Advantages not available"
        set_font(p, 12)

    add_footer(slide, f"{title} — Sales Overview")
    return slide


from pptx.oxml.xmlchemy import OxmlElement

def tighten_paragraph(p, line_spacing=0.9):
    """
    Reduces PowerPoint line spacing so long specs fit inside table cells.
    """
    pPr = p._p.get_or_add_pPr()
    lnSpc = OxmlElement("a:lnSpc")
    spcPct = OxmlElement("a:spcPct")
    spcPct.set("val", str(int(line_spacing * 100000)))
    lnSpc.append(spcPct)
    pPr.append(lnSpc)



# ===============================================================
# SLIDE 8 — PRODUCT COMPARISON (SCREENSHOT 5)
# ===============================================================
def slide_comparison(prs, products, specs_list):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_soft_gradient_background(slide)

    # -----------------------------
    # TITLE
    # -----------------------------
    header_box = slide.shapes.add_textbox(
        Inches(0.6), Inches(0.6), Inches(9), Inches(0.6)
    )
    tf = header_box.text_frame
    p = tf.paragraphs[0]
    p.text = "Product Comparison"
    p.font.name = FONT_NAME
    p.font.size = Pt(22)
    p.font.bold = True
    p.font.color.rgb = BRAND_PRIMARY
    p.alignment = PP_ALIGN.LEFT

    # -----------------------------
    # HARD SAFE TABLE BOUNDARY
    # -----------------------------
    table_left   = Inches(0.6)
    table_top    = Inches(1.4)
    table_width  = Inches(8.8)
    table_height = Inches(5.0)   # ✅ slightly reduced for safety

    # -----------------------------
    # PREPARE DATA (LIMIT ROWS)
    # -----------------------------
    all_keys = []
    for specs in specs_list:
        for k in specs:
            if k not in all_keys:
                all_keys.append(k)

    MAX_ROWS = 9     # ✅ CRITICAL: prevents overflow
    all_keys = all_keys[:MAX_ROWS]

    rows = len(all_keys) + 1
    cols = len(products) + 1

    table = slide.shapes.add_table(
        rows, cols, table_left, table_top, table_width, table_height
    ).table

    # -----------------------------
    # COLUMN WIDTHS (STATIC SAFE)
    # -----------------------------
    table.columns[0].width = Inches(1.6)

    col_width = int((table_width - Inches(1.6)) / (cols - 1))

    for c in range(1, cols):
        table.columns[c].width = col_width


    # -----------------------------
    # HEADER ROW
    # -----------------------------
    header_bg = RGBColor(80, 130, 190)
    header_text = RGBColor(255, 255, 255)

    for c in range(cols):
        cell = table.cell(0, c)
        cell.fill.solid()
        cell.fill.fore_color.rgb = header_bg
        tf = cell.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.font.name = FONT_NAME
        p.font.size = Pt(9)
        tighten_paragraph(p, 0.85)
        p.font.bold = True
        p.font.color.rgb = header_text
        p.alignment = PP_ALIGN.LEFT

    table.cell(0, 0).text = "Feature"

    for i, prod in enumerate(products):
        name = prod.get("model") or prod.get("product_name") or f"Product {i+1}"
        table.cell(0, i + 1).text = name[:28]   # ✅ truncate header safely

    # -----------------------------
    # BODY ROWS (STRICT TEXT LIMIT)
    # -----------------------------
    row_bg_1 = RGBColor(230, 235, 245)
    row_bg_2 = RGBColor(245, 247, 252)

    for r, key in enumerate(all_keys, start=1):
        bg = row_bg_1 if r % 2 else row_bg_2

        # Feature name
        cell = table.cell(r, 0)
        cell.text = key[:20]
        cell.fill.solid()
        cell.fill.fore_color.rgb = bg

        tf = cell.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.font.size = Pt(8)
        tighten_paragraph(p, 0.85)
        p.font.bold = True

        # Product values
        for c, specs in enumerate(specs_list, start=1):
            raw_val = str(specs.get(key, "N/A"))

            # ✅ HARD TEXT CLAMP (MOST IMPORTANT FIX)
            safe_val = raw_val.replace("\n", " ").strip()
            safe_val = safe_val[:140]   # prevents vertical explosion

            cell = table.cell(r, c)
            cell.text = safe_val
            cell.fill.solid()
            cell.fill.fore_color.rgb = bg

            tf = cell.text_frame
            tf.word_wrap = True
            p = tf.paragraphs[0]
            p.font.size = Pt(7)          # ✅ VERY IMPORTANT
            p.font.bold = False
            p.font.color.rgb = TEXT_COLOR
            p.alignment = PP_ALIGN.LEFT
            tighten_paragraph(p, 0.8)   # ✅ compress vertical spacing


    # -----------------------------
    # FOOTER
    # -----------------------------
    add_footer(slide, "Comparison Across Recommended Products")
    return slide




# ===============================================================
# UNIVERSAL HELPERS FOR UPSELL SLIDES  (UPDATED)
# ===============================================================
EMU_PER_INCH = 914400
def to_emu(value_in_inches: float) -> int:
    return int(value_in_inches * EMU_PER_INCH)



def one_line_ellipsis(text, limit=85):
    """
    Forces text into a single visual line with ... at the end.
    """
    if not text:
        return ""
    text = text.replace("\n", " ").strip()
    if len(text) <= limit:
        return text
    return text[:limit - 3].rstrip() + "..."





def add_image_in_box(slide, left_in, top_in, width_in, height_in, image_path):
    """Strictly clamps image inside the given box. ZERO overflow guaranteed."""
    if not image_path:
        return

    try:
        if os.path.exists(image_path):
            img_bytes = image_path
        else:
            r = requests.get(image_path, timeout=5)
            r.raise_for_status()
            img_bytes = BytesIO(r.content)

        L = to_emu(left_in)
        T = to_emu(top_in)
        W = to_emu(width_in)
        H = to_emu(height_in)

        pic = slide.shapes.add_picture(img_bytes, L, T)

        img_ratio = pic.width / pic.height
        box_ratio = W / H

        if img_ratio > box_ratio:
            pic.width = W
            pic.height = int(W / img_ratio)
        else:
            pic.height = H
            pic.width = int(H * img_ratio)

        pic.left = L + int((W - pic.width) / 2)
        pic.top  = T + int((H - pic.height) / 2)

    except Exception as e:
        print(f"[IMAGE ERROR] {image_path}: {e}")



def add_text_in_box(
    slide,
    left_in,
    top_in,
    width_in,
    height_in,
    text,
    size=12,
    bold=False,
    align="left",
    color=None,
):
    textbox = slide.shapes.add_textbox(
        to_emu(left_in), to_emu(top_in),
        to_emu(width_in), to_emu(height_in)
    )

    tf = textbox.text_frame
    tf.word_wrap = True
    tf.auto_size = None   # 🔒 prevents PowerPoint from resizing boxes

    p = tf.paragraphs[0]
    p.text = (text or "").replace("\n", " ")
    p.font.name = FONT_NAME
    p.font.size = Pt(size)
    p.font.bold = bold
    p.font.color.rgb = color or TEXT_COLOR

    if align.lower() == "center":
        p.alignment = PP_ALIGN.CENTER
    elif align.lower() == "right":
        p.alignment = PP_ALIGN.RIGHT
    else:
        p.alignment = PP_ALIGN.LEFT



def build_upsell_slides(prs, upsell_structured):

    if not upsell_structured:
        return prs

    SLIDE_WIDTH_IN = 10.0
    margin_left = 0.7
    margin_right = 0.7
    usable_width = SLIDE_WIDTH_IN - margin_left - margin_right

    PRODUCTS_PER_COLUMN = 3
    slide_num = 1

    for start in range(0, len(upsell_structured), 3):
        remaining = len(upsell_structured) - start
        cols_this_slide = 3 if remaining >= 3 else remaining

        col_width = usable_width / cols_this_slide
        total_cols_width = col_width * cols_this_slide
        left_offset = (SLIDE_WIDTH_IN - total_cols_width) / 2.0

        slide = prs.slides.add_slide(prs.slide_layouts[6])
        apply_soft_gradient_background(slide)

        # ---------- HEADER ----------
        header_box = slide.shapes.add_textbox(
            Inches(0.8), Inches(0.6), Inches(8.5), Inches(0.6)
        )
        tf = header_box.text_frame
        tf.text = f"Upsell Recommendations — Page {slide_num}"
        p = tf.paragraphs[0]
        p.font.name = FONT_NAME
        p.font.size = Pt(26)
        p.font.bold = True
        p.font.color.rgb = BRAND_PRIMARY

        # ===== LEFT-ALIGNED PROFESSIONAL GRID =====
        CATEGORY_TITLE_TOP = 1.25
        GRID_TOP = 1.90

        PRODUCT_BLOCK_HEIGHT = 1.45
        CARD_HEIGHT = 0.95
        CARD_WIDTH  = 1.35
        NAME_HEIGHT = 0.32

        for col_index, category in enumerate(
            upsell_structured[start : start + cols_this_slide]
        ):
            col_left = left_offset + col_index * col_width

            # ✅ LEFT ALIGNED CATEGORY TITLE
            add_text_in_box(
                slide,
                col_left,
                CATEGORY_TITLE_TOP,
                col_width,
                0.35,
                category.get("category", ""),
                size=17,
                bold=True,
                align="left",      # ✅ LEFT NOW
                color=BRAND_PRIMARY,
            )

            products = category.get("products", [])[:PRODUCTS_PER_COLUMN]

            for row_index, product in enumerate(products):

                product_top = GRID_TOP + row_index * PRODUCT_BLOCK_HEIGHT

                # ---------- IMAGE CARD (LEFT ALIGNED) ----------
                card_left = col_left
                card_top  = product_top

                add_white_card(
                    slide,
                    to_emu(card_left),
                    to_emu(card_top),
                    to_emu(CARD_WIDTH),
                    to_emu(CARD_HEIGHT),
                )

                # ---------- IMAGE (LEFT PADDED INSIDE CARD) ----------
                add_image_in_box(
                    slide,
                    card_left + 0.18,
                    card_top + 0.14,
                    CARD_WIDTH  - 0.36,
                    CARD_HEIGHT - 0.30,
                    product.get("image_path"),
                )

                # ---------- PRODUCT NAME (LEFT, MATCHES IMAGE) ----------
                name_top = card_top + CARD_HEIGHT + 0.06
                add_text_in_box(
                    slide,
                    col_left,
                    name_top,
                    col_width,
                    NAME_HEIGHT,
                    product.get("product_name", "Unnamed Product"),
                    size=12,
                    bold=True,
                    align="left",     # ✅ ALREADY LEFT
                )

        slide_num += 1

    return prs



# ===============================================================
# SLIDE 11 — CONCLUSION (SCREENSHOT 8)
# ===============================================================
def slide_conclusion(prs, conclusion_text=None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    apply_soft_gradient_background(slide)

    box_width = Inches(8)
    box_height = Inches(1.5)

    box_left = (SLIDE_WIDTH - box_width) / 2
    box_top  = (SLIDE_HEIGHT - box_height) / 2

    box = slide.shapes.add_textbox(
        box_left,
        box_top,
        box_width,
        box_height
    )

    tf = box.text_frame
    tf.clear()

    p = tf.paragraphs[0]
    p.text = "Thank You — HP Sales Team"
    p.alignment = PP_ALIGN.CENTER
    set_font(p, 28, bold=True, color=BRAND_PRIMARY)

    return slide


# ===============================================================
# MAIN GENERATOR
# ===============================================================
def create_professional_ppt(
    sales_pitch=None,
    products=None,
    customer_query=None,
    output_file=None
):
    print("\n=== DEBUG: SALES PITCH ===")
    print(json.dumps(sales_pitch, indent=4) if sales_pitch else "None")

    print("\n=== DEBUG: PRODUCTS ===")
    for p in products or []:
        print(json.dumps(p, indent=4))

    print("\n=== DEBUG: QUERY ===")
    print(customer_query)

    # Normalize Inputs
    pdf_title = sales_pitch.get("pitch_summary", "HP Proposal") if sales_pitch else "HP Proposal"
    extracted_requirements = sales_pitch.get("extracted_requirements", {})
    upsell_products = sales_pitch.get("upsell_opportunities", {})
    conclusion_text = sales_pitch.get("conclusion", "Recommended next steps")
    products = products or []
    output_file = output_file or "HP_Proposal.pptx"
    customer_query = customer_query or ""

    prs = Presentation()

    # Slide order matching your screenshots:
    # 0: static cover
    # 1: intro text
    # 2: customer requirements
    slide_static_cover(prs)          # screenshot 1
    slide_intro(prs, pdf_title)      # screenshot 2
    slide_requirements(prs, customer_query, extracted_requirements)  # screenshot 3

    # Product slides (screenshots 4, 4, 4, ...)
    for prod in products[:5]:
        slide_product(prs, prod, sales_pitch)

    # Build specs dicts from spec_* keys
    def extract_specs(product):
        specs = {}
        for key, value in product.items():
            if key.startswith("spec_") and value:
                clean_key = key.replace("spec_", "").replace("_", " ").title()

                text = str(value).replace("\n", " ").strip()
                text = text[:160]   # ✅ hard safety clamp

                specs[clean_key] = text
        return specs


    specs_list = []
    for p in products:
        p["specs"] = extract_specs(p)
        specs_list.append(p["specs"])

    # Comparison slide (screenshot 5)
    slide_comparison(prs, products, specs_list)

    # Upsell slides (screenshots 6 & 7)
    structured_upsell = upsell_products.get("structured", [])
    build_upsell_slides(prs, structured_upsell)

    # Conclusion (screenshot 8)
    slide_conclusion(prs, conclusion_text)

    prs.save(output_file)
    print("\n🎉 SUCCESS: PowerPoint generated →", output_file)
    return output_file
