# backend/app/utils/ppt_generator.py
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
import textwrap
import os

# ---------------------
# Configuration (tweakable)
# ---------------------
BRAND_PRIMARY = RGBColor(0, 66, 121)     # HP-like deep blue
BRAND_SECONDARY = RGBColor(0, 132, 180)  # lighter blue accent
TEXT_COLOR = RGBColor(34, 34, 34)
FOOTER_COLOR = RGBColor(120, 120, 120)
FONT_NAME = 'Calibri'                    # safe default; change to a corporate font if available
LOGO_PATH = None                         # set to your logo path (e.g. "assets/hp_logo.png") if available

# Utility: safe text wrapper
def wrap_text(s, width=80):
    if not s:
        return ""
    return "\n".join(textwrap.wrap(s, width=width))

# Helper: set paragraph font quickly
def set_paragraph_font(paragraph, size_pt=12, bold=False, color=TEXT_COLOR):
    for run in paragraph.runs:
        run.font.name = FONT_NAME
        run.font.size = Pt(size_pt)
        run.font.bold = bold
        run.font.color.rgb = color

# Create and style a title slide
def add_title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank layout
    # Title box
    left, top, width, height = Inches(0.6), Inches(0.6), Inches(8.0), Inches(1.2)
    title_box = slide.shapes.add_textbox(left, top, width, height)
    tf = title_box.text_frame
    tf.text = title
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.LEFT
    set_paragraph_font(p, size_pt=32, bold=True, color=BRAND_PRIMARY)
    # Subtitle
    left, top, width, height = Inches(0.6), Inches(1.6), Inches(8.0), Inches(1.0)
    sub_box = slide.shapes.add_textbox(left, top, width, height)
    stf = sub_box.text_frame
    stf.text = subtitle
    sp = stf.paragraphs[0]
    set_paragraph_font(sp, size_pt=14, bold=False, color=FOOTER_COLOR)
    # Footer / small brand text
    add_footer(slide, "Generated by HP AI Sales Assistant")
    # Optional logo
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        try:
            slide.shapes.add_picture(LOGO_PATH, Inches(9.0), Inches(0.2), height=Inches(0.8))
        except Exception:
            pass
    return slide

# Footer function
def add_footer(slide, footer_text):
    left, top, width, height = Inches(0.6), Inches(7.0), Inches(9.0), Inches(0.5)
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.text = footer_text
    p = tf.paragraphs[0]
    p.alignment = PP_ALIGN.LEFT
    set_paragraph_font(p, size_pt=9, bold=False, color=FOOTER_COLOR)

# Executive summary slide
def add_executive_summary(prs, summary_text, highlights):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    left, top = Inches(0.6), Inches(0.6)
    # Header
    header = slide.shapes.add_textbox(left, top, Inches(8.5), Inches(0.5)).text_frame
    header.text = "Executive Summary"
    set_paragraph_font(header.paragraphs[0], size_pt=20, bold=True, color=BRAND_PRIMARY)
    # Summary
    st = wrap_text(summary_text, 120)
    body = slide.shapes.add_textbox(left, Inches(1.2), Inches(5.0), Inches(3.2)).text_frame
    body.text = st
    set_paragraph_font(body.paragraphs[0], size_pt=12)
    # Highlights (bullet column on right)
    right_box = slide.shapes.add_textbox(Inches(6.8), Inches(1.2), Inches(3.0), Inches(3.2))
    rtf = right_box.text_frame
    rtf.text = "Key Highlights"
    set_paragraph_font(rtf.paragraphs[0], size_pt=14, bold=True, color=BRAND_SECONDARY)
    for h in highlights or []:
        p = rtf.add_paragraph()
        p.text = f"• {h}"
        p.level = 1
        set_paragraph_font(p, size_pt=12)
    add_footer(slide, "Executive Summary • Tailored to customer requirements")
    return slide

# Product feature slide (compact card layout)
def add_product_slide(prs, product):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    left_margin = 0.5
    top = 0.5
    # Header
    header = slide.shapes.add_textbox(Inches(left_margin), Inches(top), Inches(9.0), Inches(0.4)).text_frame
    header.text = product.get("model", product.get("product_name", "Unknown Model"))
    set_paragraph_font(header.paragraphs[0], size_pt=18, bold=True, color=BRAND_PRIMARY)
    # Left column: description + bullets
    desc = product.get("text_content") or product.get("description") or ""
    desc = wrap_text(desc, 120)[:800]
    left_box = slide.shapes.add_textbox(Inches(left_margin), Inches(top + 0.6), Inches(5.4), Inches(3.5))
    ltf = left_box.text_frame
    ltf.text = desc if len(desc) > 0 else "No description available."
    set_paragraph_font(ltf.paragraphs[0], size_pt=11)
    # Specs: prioritized
    specs = product.get("specs", {}) or {}
    if specs:
        p = ltf.add_paragraph()
        p.text = ""
        p = ltf.add_paragraph()
        p.text = "Key Specs:"
        set_paragraph_font(p, size_pt=13, bold=True, color=BRAND_SECONDARY)
        # pick top specs by common keys
        priority_keys = ["Processor", "CPU", "Graphics", "GPU", "Memory", "RAM", "Storage", "Display", "Weight", "Operating system", "OS"]
        shown = 0
        for pk in priority_keys:
            for k, v in list(specs.items()):
                if pk.lower() in k.lower() and shown < 5:
                    sp = ltf.add_paragraph()
                    sp.text = f"• {k}: {v}"
                    set_paragraph_font(sp, size_pt=11)
                    shown += 1
        # Fill with remaining if not enough
        if shown < 5:
            for k, v in specs.items():
                if shown >= 5:
                    break
                if any(pk.lower() in k.lower() for pk in priority_keys):
                    continue
                sp = ltf.add_paragraph()
                sp.text = f"• {k}: {v}"
                set_paragraph_font(sp, size_pt=11)
                shown += 1
    # Right column: image and quick bullets
    img_path = product.get("image_path")
    if img_path and os.path.exists(img_path):
        try:
            slide.shapes.add_picture(img_path, Inches(6.2), Inches(1.2), height=Inches(3.2))
        except Exception:
            pass
    # Quick bullets area under image
    right_box = slide.shapes.add_textbox(Inches(6.2), Inches(4.5), Inches(3.2), Inches(1.2)).text_frame
    rb = right_box.paragraphs[0]
    rb.text = "Selling Points"
    set_paragraph_font(rb, size_pt=12, bold=True, color=BRAND_SECONDARY)
    bullets = product.get("selling_points", [])[:4]
    for b in bullets:
        p = right_box.add_paragraph()
        p.text = f"• {b}"
        set_paragraph_font(p, size_pt=11)
    add_footer(slide, f"{product.get('model', product.get('product_name',''))} • Product Sheet")
    return slide

# Comparison table slide (professional style)
def add_comparison_slide(prs, products, keys=None):
    if keys is None:
        keys = ["Operating system", "Processor", "Memory", "Graphics", "Storage", "Weight", "Power"]

    slide = prs.slides.add_slide(prs.slide_layouts[6])
    # Title
    title_tf = slide.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(9.0), Inches(0.4)).text_frame
    title_tf.text = "Technical Comparison"
    set_paragraph_font(title_tf.paragraphs[0], size_pt=20, bold=True, color=BRAND_PRIMARY)
    # Table geometry
    rows = len(keys) + 1
    cols = len(products) + 1
    left, top, width, height = Inches(0.4), Inches(1.3), Inches(9.2), Inches(4.2)
    table_shape = slide.shapes.add_table(rows, cols, left, top, width, height)
    table = table_shape.table
    # Headers
    table.cell(0, 0).text = "Feature"
    set_paragraph_font(table.cell(0, 0).text_frame.paragraphs[0], size_pt=11, bold=True, color=BRAND_SECONDARY)
    for i, prod in enumerate(products):
        cell = table.cell(0, i+1)
        name = prod.get("model") or prod.get("product_name") or f"Product {i+1}"
        cell.text = name
        set_paragraph_font(cell.text_frame.paragraphs[0], size_pt=11, bold=True)
    # Fill rows
    for r_idx, key in enumerate(keys):
        table.cell(r_idx+1, 0).text = key
        set_paragraph_font(table.cell(r_idx+1, 0).text_frame.paragraphs[0], size_pt=10, bold=True)
        for c_idx, prod in enumerate(products):
            val = "N/A"
            for sk, sv in prod.get("specs", {}).items():
                if key.lower() in sk.lower():
                    val = sv
                    break
            cell = table.cell(r_idx+1, c_idx+1)
            # small text, truncated
            v = (val[:80] + "...") if isinstance(val, str) and len(val) > 80 else str(val)
            cell.text = v
            set_paragraph_font(cell.text_frame.paragraphs[0], size_pt=9)
    add_footer(slide, "Technical Comparison • Data extracted from product specs")
    return slide

# Sales pitch / Competitive advantages slide
def add_sales_pitch_slide(prs, pitch_dict):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    # Title
    title_box = slide.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(9.0), Inches(0.4)).text_frame
    title_box.text = "Sales Pitch & Competitive Advantages"
    set_paragraph_font(title_box.paragraphs[0], size_pt=20, bold=True, color=BRAND_PRIMARY)

    # Left: Pitch summary
    left_box = slide.shapes.add_textbox(Inches(0.6), Inches(1.1), Inches(5.5), Inches(2.6)).text_frame
    left_box.text = pitch_dict.get("pitch_summary", "No pitch summary available.")
    set_paragraph_font(left_box.paragraphs[0], size_pt=12)

    # Right: bulleted lists (reasons, upsell, competitive)
    right_box = slide.shapes.add_textbox(Inches(6.2), Inches(1.1), Inches(3.6), Inches(3.6))
    rtf = right_box.text_frame
    rtf.text = "Key Benefits"
    set_paragraph_font(rtf.paragraphs[0], size_pt=13, bold=True, color=BRAND_SECONDARY)

    # product_highlights
    for h in pitch_dict.get("product_highlights", [])[:4]:
        p = rtf.add_paragraph()
        p.text = f"• {h}"
        set_paragraph_font(p, size_pt=11)

    # next block: competitive advantages (new slide if too long)
    # show up to 4 on the same slide
    comp = pitch_dict.get("competitive_advantages", [])[:4]
    if comp:
        # stretch area lower
        rtf2 = slide.shapes.add_textbox(Inches(0.6), Inches(3.6), Inches(9.0), Inches(1.6)).text_frame
        rtf2.text = "Competitive Advantages"
        set_paragraph_font(rtf2.paragraphs[0], size_pt=13, bold=True, color=BRAND_SECONDARY)
        for ca in comp:
            p = rtf2.add_paragraph()
            p.text = f"• {ca}"
            set_paragraph_font(p, size_pt=11)

    add_footer(slide, "Sales Pitch • Tailored by AI Sales Assistant")
    return slide

# Pricing slide (dynamic)
def add_pricing_slide(prs, products):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    header = slide.shapes.add_textbox(Inches(0.6), Inches(0.5), Inches(9.0), Inches(0.4)).text_frame
    header.text = "Pricing & Availability"
    set_paragraph_font(header.paragraphs[0], size_pt=20, bold=True, color=BRAND_PRIMARY)
    body = slide.shapes.add_textbox(Inches(0.6), Inches(1.2), Inches(9.0), Inches(3.0)).text_frame
    body.text = "Contact Sales for best quotation and lead times. Suggested starting points:"
    set_paragraph_font(body.paragraphs[0], size_pt=12)
    for p in products:
        model = p.get("model") or p.get("product_name")
        price = p.get("price", "Contact Sales")
        line = body.add_paragraph()
        line.text = f"• {model}: {price}"
        set_paragraph_font(line, size_pt=11)
    add_footer(slide, "Pricing indicative; contact HP Sales for firm quotation.")
    return slide

# Closing / CTA slide
def add_closing_slide(prs, cta_text=None):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    header = slide.shapes.add_textbox(Inches(0.6), Inches(1.0), Inches(9.0), Inches(0.6)).text_frame
    header.text = "Next Steps & Call to Action"
    set_paragraph_font(header.paragraphs[0], size_pt=22, bold=True, color=BRAND_PRIMARY)
    body = slide.shapes.add_textbox(Inches(0.6), Inches(1.6), Inches(9.0), Inches(2.8)).text_frame
    default_cta = (
        "1) Confirm shortlist and configuration\n"
        "2) Request formal quote and lead time\n"
        "3) Schedule an on-site demo or workshop\n\n"
        "Contact: HP Sales Representative"
    )
    body.text = cta_text or default_cta
    set_paragraph_font(body.paragraphs[0], size_pt=12)
    add_footer(slide, "Thank you — HP Sales Team")
    return slide

# Main generator function - accepts sales_pitch (dict) and products (list of dicts)
def create_professional_ppt(sales_pitch, products, customer_query, output_file="HP_Proposal_Professional.pptx"):
    prs = Presentation()
    # Title slide
    title = f"{sales_pitch.get('pitch_summary','HP Workstation Solutions')[:60]}"
    subtitle = f"Proposal for: {customer_query}"
    add_title_slide(prs, title, subtitle)
    # Executive summary
    add_executive_summary(prs, sales_pitch.get("pitch_summary",""), sales_pitch.get("product_highlights",[]))
    # Product slides - top N products (limit to 6 for deck length)
    for prod in products[:6]:
        add_product_slide(prs, prod)
    # Sales pitch slide
    add_sales_pitch_slide(prs, sales_pitch)
    # Comparison slide using top 3 products
    add_comparison_slide(prs, products[:3])
    # Pricing and upsell
    add_pricing_slide(prs, products[:4])
    # Upsell opportunities slide
    if sales_pitch.get("upsell_opportunities"):
        upsell_slide = prs.slides.add_slide(prs.slide_layouts[6])
        utf = upsell_slide.shapes.add_textbox(Inches(0.6), Inches(0.6), Inches(9.0), Inches(0.4)).text_frame
        utf.text = "Upsell & Cross-sell Opportunities"
        set_paragraph_font(utf.paragraphs[0], size_pt=20, bold=True, color=BRAND_PRIMARY)
        body = upsell_slide.shapes.add_textbox(Inches(0.6), Inches(1.2), Inches(9.0), Inches(3.6)).text_frame
        body.text = ""
        for up in sales_pitch.get("upsell_opportunities", []):
            p = body.add_paragraph()
            p.text = f"• {up}"
            set_paragraph_font(p, size_pt=12)
        add_footer(upsell_slide, "Suggested bundles to increase deal value")
    # Closing slide
    add_closing_slide(prs, sales_pitch.get("call_to_action"))
    # Save deck
    prs.save(output_file)
    print(f"🎉 Professional presentation saved to: {output_file}")
    return output_file

# Example usage (uncomment to test locally)
# if __name__ == "__main__":
#     import json
#     # load a sales_pitch dict and products list
#     with open("/mnt/data/hp catalogue_output.json","r",encoding="utf-8-sig") as f:
#         pages = json.load(f)
#     # Build minimal example products and sales_pitch from your pipeline before calling
#     # create_professional_ppt(sales_pitch, products, "I need a powerful workstation for CAD")
